ADD: radiobutton for application mode list in UI & api-address flag in settings. А так же рефакторинг табов на пробелы Расширение описания для подсказок в расширенных настройках Смена тестовой JS библиотеки на более легковесную Убрал от греха подальше стратегию Direct для Tun2Proxy Добавил интерактив для API/IP флага "api-address" и информацию по подключению к серверам И боже мой, как же я "обожаю" XML разметку, для рисования кнопок.

diff --git a/.github/workflows/BuildFromSourceDebug_tun2proxy.yml b/.github/workflows/BuildFromSourceDebug_tun2proxy.yml
--- a/.github/workflows/BuildFromSourceDebug_tun2proxy.yml
+++ b/.github/workflows/BuildFromSourceDebug_tun2proxy.yml
@@ -9,19 +9,19 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    # 1. Скачиваем ваш код из репозитория
-    - uses: actions/checkout@v3
+    # 1. Загружаем код из репозитория
+    - uses: actions/checkout@v6.0.1
 
     # 2. Настраиваем Java 17
     - name: set up JDK 17
-      uses: actions/setup-java@v3
+      uses: actions/setup-java@v5.1.0
       with:
         java-version: '17'
         distribution: 'temurin'
     
     # 3. Настраиваем Gradle 8.5
     - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@v3
+      uses: gradle/actions/setup-gradle@v5
       with:
         gradle-version: '8.5'
 
@@ -97,11 +97,15 @@ jobs:
            
     # 6. Извлекаем версию из Gradle
     - name: Extract Version Name
+      id: extract_version
       run: |
-        echo "Extracting version..."
-        VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '"' | tr -d "'")
+        VERSION_NAME=$(grep "versionName" app/build.gradle | head -n 1 | awk '{print $2}' | tr -d '"' | tr -d "'")
+        if [[ -z "$VERSION_NAME" ]]; then
+          echo "Could not extract version"
+          exit 1
+        fi
         echo "Detected App Version: $VERSION_NAME"
-        echo "APP_VERSION=$VERSION_NAME" >> $GITHUB_ENV
+        echo "APP_VERSION=${VERSION_NAME}" >> $GITHUB_ENV
 
     # 7. Сборка
     - name: Build with Gradle
@@ -113,7 +117,7 @@ jobs:
       
     # 8. Загрузка готового APK
     - name: Upload APKs
-      uses: actions/upload-artifact@v4
+      uses: actions/upload-artifact@v6.0.0
       with:
         name: Opera_Proxy_v${{ env.APP_VERSION }}
         path: |
